#!/usr/bin/env python3
"""
The markdown report of `scripts/s2_duration_compare.py` — every number is read from
`data/S2_duration_compare.json`; nothing is computed here and nothing is typed by hand.

Usage: python scripts/s2_duration_report.py [--json data/S2_duration_compare.json]
                                            [--md reports/S2_duration_and_idle_2x2.md]
"""
import argparse
import json
import os
import sys

sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "src"))
from skqd.report import md_table  # noqa: E402

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
US = 1e6


def report_text(d):
    s, v, h = d["summary"], d["verdict"], d["rescheduling_headroom"]
    rec = d["method"]["records"]
    frozen = d["circuits"]["exact|frozen|B0_ref06_k1_rep1"]

    fam_rows = []
    for key in sorted(s):
        r = s[key]
        fam_rows.append([
            r["family"], r["regime"].split(" ")[0], key.split("|")[2], r["n_circuits"],
            f"{r['T_s']['mean'] * US:.2f}", f"{r['T_total_s']['mean'] * US:.2f}",
            f"{r['depth']['mean']:.0f}", f"{r['n_cz']['mean']:.0f}",
            f"{r['cz_depth']['mean']:.0f}", f"{r['n_1q']['mean']:.0f}",
            f"{r['idle_total_s']['mean'] * US:.1f}", f"{r['idle_max_s']['mean'] * US:.1f}",
            f"{r['S_T1']['mean']:.3f}", f"{r['S_T2']['mean']:.3f}", f"{r['S_DD']['mean']:.3f}",
            f"{r['f_gates']['mean']:.4f}", f"{r['f_idle_dd_off']['mean']:.2e}",
            f"{r['yield_idle_dd_off']['mean']:.4f}"])

    gt = [["exact (frozen canary QPY)", f"{frozen['T_s'] * US:.2f}", f"{frozen['T_total_s'] * US:.2f}",
           frozen["depth"], frozen["n_cz"], frozen["cz_depth"],
           f"{frozen['idle_total_s'] * US:.1f}", f"{frozen['S_T1']:.3f}", f"{frozen['S_T2']:.3f}",
           f"{frozen['S_DD']:.3f}", f"{frozen['f_gates']:.4f}", f"{frozen['f_idle_dd_off']:.2e}"]]

    vrows = []
    for regime, r in sorted(v.items()):
        vrows.append([regime, r["n_pairs"], ", ".join(r["records"]),
                      f"{r['T_ratio_fixed_over_exact']['mean']:.3f}",
                      f"{r['depth_ratio']['mean']:.3f}", f"{r['cz_ratio']['mean']:.3f}",
                      f"{r['idle_ratio']['mean']:.3f}", f"{r['S_T1_T2_ratio']['mean']:.3f}",
                      f"{r['f_gates_ratio']['mean']:.3f}",
                      f"{r['f_idle_ratio_fixed_over_exact']['mean']:.3f}",
                      f"{r['yield_ratio']['mean']:.3f}", r["winner"],
                      f"{r['win_margin_f']:.2f}x"])

    qrows = []
    for q, x in sorted(h["per_qubit"].items(), key=lambda kv: int(kv[0])):
        qrows.append([q, f"{x['T1_s'] * US:.1f}", f"{x['T2_s'] * US:.1f}",
                      f"{x['busy_s'] * US:.2f}", f"{x['idle_s'] * US:.2f}",
                      f"{x['S_T1']:.3f}", f"{x['S_T2']:.3f}"])

    trows = [[k, n, ", ".join(str(q) for q in h["terms"]["supports"][k])]
             for k, n in sorted(h["terms"]["support_sizes"].items())]

    dd_rows = []
    for key in sorted(s):
        r = s[key]
        dd_rows.append([r["family"], r["regime"].split(" ")[0], key.split("|")[2],
                        f"{r['S_T1']['mean']:.3f}", f"{r['S_T2']['mean']:.3f}",
                        f"{r['S_DD']['mean']:.3f}",
                        f"{r['f_idle_dd_off']['mean']:.2e}"])

    # sentences whose numbers are derived from the JSON, never typed
    key_pin = next((k for k in v if k.startswith("pinned") and k.endswith("ibm_fez")), None)
    pin = v[key_pin] if key_pin else None
    sm_pin = next(s[k] for k in s if k.startswith("exact|pinned|ibm_fez"))
    q_worst = max(h["per_qubit"].items(), key=lambda kv: kv[1]["S_T2"])
    s_t2_share = q_worst[1]["S_T2"] / h["S_T2_now"]
    dj = h["terms"]["disjoint_pairs"]
    dj_txt = ("; the only disjoint pair is " + " / ".join(dj[0])) if len(dj) == 1 else (
        ("; disjoint pairs: " + "; ".join(" / ".join(p) for p in dj)) if dj else "")

    ctx = d["context"]
    env = d["environment"]
    return f"""# Circuit family under DURATION, not gate count — 2x2, {rec['ibm_fez']['last_update_date']}

Generated by `scripts/s2_duration_report.py` from `data/S2_duration_compare.json`
(`scripts/s2_duration_compare.py`, {d['created']}, commit `{env['git_commit']}`).
{d['n_circuits']} circuits, {d['runtime_s']:.0f} s, **{d['method']['qpu_time_used_s']:.0f} s of QPU time**.

{d['question']}.

Schedules and budgets are `scripts/h0_idle_model.py` **imported, not reimplemented**: the ASAP
schedule, the idle windows, {d['method']['idle_budget']}, the DD eligibility rule and the yield
model are the ones gate H0_diag was preregistered with.  The real record is
`{rec['ibm_fez']['path']}` (fingerprint `{rec['ibm_fez']['fingerprint'][:16]}`), which covers the
canary's {len(rec['ibm_fez']['covers_qubits'])} qubits and therefore carries the PINNED circuits
that route inside the patch.  The FREE layouts of the two families land on different patches, so that
regime is compared on the offline full-device `FakeFez` snapshot
({rec['FakeFez']['last_update_date']}, {rec['FakeFez']['n_qubits']} qubits); every pair in section 2
is scheduled on one and the same record.  {len(d['pinned_circuits_that_left_the_patch'])} pinned
circuits (the r = 2 and r = 3 repetitions) needed routing ancillas outside the patch and fall back to
the same snapshot.  The free-layout exact circuit at the canary's parameters reproduces the frozen
QPY exactly: **{d['free_layout_exact_reproduces_the_frozen_canary']}**.  Both families are transpiled identically to the
frozen set (optimization level {d['method']['transpiler']['optimization_level']}, seed
{d['method']['transpiler']['seed_transpiler']}).

## 0. Ground truth — the circuit the device ran

{md_table(["circuit", "T before readout (us)", "T incl. readout (us)", "depth", "CZ", "CZ layers",
           "idle summed over 12 qubits (us)", "S_T1", "S_T2", "S_DD", "f_gates", "f (idle, DD off)"], gt)}

## 1. Duration and idle budget per family

`T` is the ASAP critical path before the measure layer; `idle` is summed over the active qubits;
`S_T1`, `S_T2` are the PTA relaxation budgets of the idle windows and `S_DD` the cost of one XY4
sequence per DD-eligible window; `f_gates` is `gate_S2D.analyse_on_backend` on the record and
`f (idle)` is `f_gates x exp(-S_T1 - S_T2)`.  Means over the circuits of each group.

{md_table(["family", "layout", "record", "circuits", "T (us)", "T+readout (us)", "depth", "CZ",
           "CZ layers", "1q gates", "idle (us)", "worst-qubit idle (us)", "S_T1", "S_T2", "S_DD",
           "f_gates", "f (idle, DD off)", "yield"], fam_rows)}

## 2. Which family wins under the corrected objective

Ratios fixed-angle / exact, paired circuit by circuit (same reference, k, repetitions, same
layout regime and the same calibration record on both sides, so the only difference is the family).
A ratio below 1 means the fixed-angle family is *cheaper* in that column; for `f` and `yield` a
ratio above 1 means it is *better*.

{md_table(["layout", "pairs", "record", "T", "depth", "CZ", "idle", "S_T1+S_T2", "f_gates",
           "f (idle)", "yield", "winner", "margin in f"], vrows)}

**Verdict.** On the ibm_fez record of the day, at the production point (r = 1, both families on the
canary's own 12 qubits, {pin['n_pairs']} paired circuits), the fixed-angle generator is
**{(pin['T_ratio_fixed_over_exact']['mean'] - 1) * 100:+.1f} %** in duration and
**{(pin['idle_ratio']['mean'] - 1) * 100:+.1f} %** in summed idle time against the exact family,
for **{(pin['cz_ratio']['mean'] - 1) * 100:+.1f} %** two-qubit gates, and its idle-aware clean-shot
fraction is **{pin['f_idle_ratio_fixed_over_exact']['mean']:.3f}x** the exact family's
(yield {pin['yield_ratio']['mean']:.3f}x).  The exact family wins by
{pin['win_margin_f']:.2f}x in f.  Note the dissociation the corrected objective is about: the
fixed-angle circuits are **shallower in DAG depth**
({pin['depth_ratio']['mean']:.3f}x) and still **longer in time** — depth is not duration, because
the fixed-angle generator trades multiplexed rotations for more controls per rotation and its extra
CZ layers each cost a full CZ duration.

## 3. Re-scheduling headroom inside the exact family

The frozen canary runs {h['n_cz']} CZ in {h['cz_depth']} CZ layers
({frozen['cz_per_cz_layer']:.3f} CZ per layer), i.e. it is serial in its two-qubit gates.  Qubit-time
utilisation (busy / (qubits x T)) is **{h['qubit_time_utilisation']:.3f}**.

For *any* reordering of the same gates on the same layout, no qubit can finish before its own busy
time, so `T_min = max_q busy_q` bounds the duration from below, and the idle budget evaluated with one
window per qubit (the window structure that minimises the PTA budget at fixed total idle) bounds
`S_T1 + S_T2` from below:

{md_table(["quantity", "as scheduled", "best possible re-schedule", "available factor"],
          [["duration T (us)", f"{h['T_s'] * US:.2f}", f"{h['T_min_s'] * US:.2f}",
            f"{h['speedup_available']:.2f}x"],
           ["idle summed over the qubits (us)", f"{h['idle_total_now_s'] * US:.1f}",
            f"{h['idle_total_s'] * US:.1f}",
            f"{h['idle_total_now_s'] / h['idle_total_s']:.2f}x"],
           ["S_T1", f"{h['S_T1_now']:.3f}", f"{h['S_T1']:.3f}",
            f"{h['S_T1_now'] / h['S_T1']:.2f}x"],
           ["S_T2", f"{h['S_T2_now']:.3f}", f"{h['S_T2']:.3f}",
            f"{h['S_T2_now'] / h['S_T2']:.2f}x"],
           ["f (idle, DD off)", f"{frozen['f_idle_dd_off']:.2e}", f"{h['f_idle_dd_off']:.2e}",
            f"{h['f_gain']:.2f}x"]])}

Why the schedule is serial: the coarse step is a product of {h['terms']['n_terms']} term
exponentials whose qubit supports are listed below.  Only
**{h['terms']['n_disjoint_pairs']} of the {h['terms']['n_pairs']}** pairs of terms have disjoint
support{dj_txt}.  The diagonal term touches all
{h['terms']['support_sizes']['diag']} logical qubits and the plaquette
{h['terms']['support_sizes']['plaq0']}, so no term-level re-ordering can put either of them in
parallel with anything else: the overlap that serialises the circuit is a property of the
Hamiltonian's supports under this codeword layout, not of the synthesis.

One qubit dominates the T2 budget: physical qubit {q_worst[0]} (T2 =
{q_worst[1]['T2_s'] * US:.1f} us) carries {q_worst[1]['S_T2']:.3f} of the
{h['S_T2_now']:.3f} total, **{s_t2_share * 100:.0f} %**.  Patch selection on T2 is therefore a
larger lever than the family choice measured in section 2.

{md_table(["term", "support size", "qubits"], trows)}

{md_table(["physical qubit", "T1 (us)", "T2 (us)", "busy (us)", "idle (us)", "S_T1", "S_T2"], qrows)}

## 4. DD accounting

{md_table(["family", "layout", "record", "S_T1", "S_T2", "S_DD (XY4 pulse cost)", "f (idle, DD off)"], dd_rows)}

## 5. Proposed replacement wording for item 3 of the amendment

The owner merges the amendment; this is the text this measurement supports, with the figure of
merit stated as duration and idle budget instead of two-qubit gate count.  Every number in it is
the JSON's.

> **3. Circuit family, and the figure of merit by which a family is chosen.**  The circuit family
> stays the exact structured circuits of gate S2 (`validation/S2.json`,
> `skqd.circuits_ir.structured_term_gates`, `angle_mode="exact"`).  The criterion on which that
> choice rests is amended: a circuit family is judged not by its two-qubit gate count but by the
> **ASAP-scheduled duration and per-qubit idle budget** of its circuits on the calibration of the
> device that will run them —
>
>   * `T` = the ASAP critical path before the measure layer, and the idle window list of every
>     active qubit (`scripts/h0_idle_model.py` / `skqd.idle`);
>   * `S_T1 = sum_q sum_w (1 - e^(-w/T1_q))/4`, `S_T2 = sum_q sum_w (1 - e^(-w/T2_q))/2`;
>   * the idle-aware clean-shot fraction `f = f_gates x exp(-S_T1 - S_T2)`, with `f_gates` the
>     gate-and-readout product of section 1(c).
>
> Gate H0_diag (`validation/H0_diag.json`, {ctx['H0_diag']['total_usage_s']:.1f} s of QPU time on
> ibm_fez; J1 gave N1 = {ctx['H0_diag']['N1']} accepted of 2000) established
> the reason: at 2x2 the dominant loss is idle-time decoherence over the circuit's wall-clock
> duration, not the gate count.  The frozen canary runs
> {frozen['T_s'] * US:.2f} us at depth {frozen['depth']} for only {frozen['n_cz']} CZ
> ({frozen['cz_per_cz_layer']:.2f} CZ per CZ layer, qubit-time utilisation
> {h['qubit_time_utilisation']:.3f}), and its idle budget is
> {frozen['S_T1'] + frozen['S_T2']:.3f} error units ({frozen['S_T1']:.3f} + {frozen['S_T2']:.3f}),
> which is what separates the gate-only prediction from the device.  A family with fewer gates at
> the same or greater duration therefore buys nothing, and a shallower-in-time family wins even at
> equal gate count.
>
> Re-evaluated on that criterion (`data/S2_duration_compare.json`,
> `reports/S2_duration_and_idle_2x2.md`, {d['n_circuits']} circuits, no QPU time), the fixed-angle
> generator of `validation/S2_fixed.json` is **not** adopted — and now for the right reason.  With
> both families on the canary's own 12 physical qubits and the same ibm_fez calibration record
> ({pin['n_pairs']} paired circuits), the fixed-angle circuits are
> {(pin['depth_ratio']['mean'] - 1) * 100:+.1f} % in DAG depth but
> **{(pin['T_ratio_fixed_over_exact']['mean'] - 1) * 100:+.1f} % in duration**,
> {(pin['idle_ratio']['mean'] - 1) * 100:+.1f} % in summed idle time and
> {(pin['cz_ratio']['mean'] - 1) * 100:+.1f} % in CZ, reaching
> {pin['f_idle_ratio_fixed_over_exact']['mean']:.3f}x the exact family's idle-aware f.  They are not
> shallower in time, so the earlier rejection on routed CZ count is confirmed rather than reversed;
> their known cost (a different generator: worst per-term deviation
> {ctx['S2_fixed']['max_per_term_deviation_2x2']:.3f} at 2x2 against
> {ctx['S2']['max_deviation']:.1e} for the exact family, with gate-S1 recall
> {ctx['S2_fixed']['recall_2x3_B0']:.3f} / {ctx['S2_fixed']['recall_2x3_B1']:.3f} preserved) is not
> incurred.  For the record, the gate counts on which item 3 was originally decided are
> {ctx['S2']['cz_all_to_all_2x2']} all-to-all / {ctx['S2']['cz_routed_2x2']} routed CZ per 2x2
> coarse step for the exact family and {ctx['S2_fixed']['cz_all_to_all_2x2']} /
> {ctx['S2_fixed']['cz_routed_2x2']} for the fixed-angle one (`validation/S2.json`,
> `validation/S2_fixed.json`).
>
> This item does **not** claim that the exact family is adequate at 2x2 on the present device:
> at the production point it reaches an idle-aware f of {sm_pin['f_idle_dd_off']['mean']:.2e}
> (mean over {sm_pin['n_circuits']} circuits) against the f >= 0.1 of item 2.  What moves that
> number is duration and patch quality, not the family — see item 3(b).
>
> **3(b). Re-scheduling headroom (measured, no new decomposition).**  On the same gates and the same
> layout, no qubit can finish before its own busy time, so the duration cannot fall below
> `T_min = max_q busy_q` = {h['T_min_s'] * US:.2f} us against the {h['T_s'] * US:.2f} us the ASAP
> schedule takes: a perfect re-schedule is worth at most **{h['speedup_available']:.2f}x** in
> duration, {h['S_T1_now'] / h['S_T1']:.2f}x in S_T1, {h['S_T2_now'] / h['S_T2']:.2f}x in S_T2 and
> **{h['f_gain']:.2f}x** in f — which does not reach f >= 0.1 either.  That bound is not attainable:
> only {h['terms']['n_disjoint_pairs']} of the {h['terms']['n_pairs']} pairs of Hamiltonian terms
> have disjoint support, and the diagonal and plaquette terms touch
> {h['terms']['support_sizes']['diag']} and {h['terms']['support_sizes']['plaq0']} of the 12 logical
> qubits.  Reaching it would require a different codeword layout (`skqd.codec`, which re-opens
> E1–E3), not a re-ordering of the present one.  Qubit {q_worst[0]} alone
> (T2 = {q_worst[1]['T2_s'] * US:.1f} us) carries {s_t2_share * 100:.0f} % of S_T2, so patch
> selection on T2 is the larger lever and is already covered by item 1.

---

Every number above is read from `data/S2_duration_compare.json`.  Environment: Python
{env['python']}, numpy {env['numpy']}, {env['platform']}, {env['cpu_count']} CPUs,
{env['timestamp']}.
"""


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--json", default=os.path.join("data", "S2_duration_compare.json"))
    ap.add_argument("--md", default=os.path.join("reports", "S2_duration_and_idle_2x2.md"))
    a = ap.parse_args()
    p = a.json if os.path.isabs(a.json) else os.path.join(ROOT, a.json)
    with open(p) as fh:
        d = json.load(fh)
    mp = a.md if os.path.isabs(a.md) else os.path.join(ROOT, a.md)
    os.makedirs(os.path.dirname(mp), exist_ok=True)
    with open(mp, "w") as fh:
        fh.write(report_text(d))
    print(f"wrote {os.path.relpath(mp, ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
