#!/usr/bin/env python3
"""Regenerate validation/gates.md and reports/PROJECT_STATUS.md from validation/*.json (no hand-typed numbers)."""
import glob
import json
import os
import time

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
GATES = [  # gate, description (manual Step 10), where it runs
    ("E1", "[G_a(x),H]=0; 82-dim kernel; sector split; two builders agree to 1e-12", "cloud/laptop CPU"),
    ("E2", "counts of Table 2; codec round trip on all 2x3 states; random-bitstring acceptance ~0.15%", "cloud/laptop CPU"),
    ("E3", "2x3 and 2x4 references (Table 1); static sectors; dt = pi/W per sector", "cloud/laptop CPU"),
    ("S1", "emulated support recall >= 0.9 at f >= 0.1 with the production budget; controls table", "cloud/laptop CPU"),
    ("CS", "structure of the terms in codeword space (input to S2)", "cloud/laptop CPU"),
    ("L2", "Qiskit circuits reproduce the numpy reference at 2x2", "laptop"),
    ("L3", "transpiled CZ counts (S2 measurement)", "laptop"),
    ("L4", "Aer noise-model sampling at 2x2 (S3 preparation)", "laptop"),
    ("L5", "CUDA-Q circuits reproduce the numpy reference at 2x2", "laptop GPU"),
    ("S2", "routed CZ per coarse step <= 500 on the target map (<= 250 at 2x2); compiled circuits leak-free", "laptop"),
    ("S3", "Aer device-model recall >= 0.9 for the production set; shot budget fixed", "desktop GPU"),
    ("H0", "2x2 hardware: decoder validity, bit order, parity checks; measured f within 30% of the model", "QPU"),
    ("H1", "2x3 B=0: certified interval of width <= 0.1 containing the exact E0; recall >= 0.8", "QPU"),
    ("H2", "2x3 B=1: cluster energy certified to +-rH <= 0.15; V(1), V(2) intervals containing exact values", "QPU"),
    ("P1", "primary endpoint curves with bootstrap bands", "laptop"),
    ("M1", "ML uses credited only under Step 7.5", "desktop GPU"),
]


def main():
    rows = []
    for g, desc, where in GATES:
        p = os.path.join(ROOT, "validation", f"{g}.json")
        if os.path.exists(p):
            d = json.load(open(p))
            nf = sum(1 for c in d["criteria"] if not c["passed"])
            status = f"**{d['status']}** ({len(d['criteria'])} criteria, {nf} failing, {d['runtime_s']:.0f} s, {d['environment']['timestamp']}, commit {d['environment']['git_commit']})"
        else:
            status = "open"
        rows.append(f"| {g} | {desc} | {where} | {status} |")
    table = "| gate | check (manual Step 10) | runs on | status |\n|---|---|---|---|\n" + "\n".join(rows)
    stamp = time.strftime("%Y-%m-%d %H:%M UTC", time.gmtime())
    open(os.path.join(ROOT, "validation", "gates.md"), "w").write(f"# Gate table (generated by scripts/update_status.py, {stamp})\n\n{table}\n")
    status = f"""# Project status (generated by scripts/update_status.py, {stamp})

{table}

## Reports

| report | content |
|---|---|
| `reports/E1_gauss_law_two_builders.md` | Gauss law, kernel, two-builder agreement, 2x2 spectrum vs manual |
| `reports/E2_counts_codewords_decoder.md` | Table 2, vertex tables, codewords, decoder acceptance |
| `reports/E3_exact_references.md` | Table 1, static sectors, derived quantities, clusters, j_max=1 truncation |
| `reports/S1_support_emulation_controls.md` | reachability, Table 4, production-budget recall, Table 3, ML ranker, 2x4 |
| `reports/circuit_structure.md` | term structure in codeword space, 2x2 plaquette pair rotation, IR gate counts |
| `reports/laptop_vs_hpc_plan.md` | what runs on the laptop within 30 min and what needs desktop/cluster/QPU |
| `reports/L*.md` | laptop gates (written when they run) |

## Next actions (prompts/)

00 bootstrap + push → 01 L1 reproduce → 02 L2 Qiskit → 03 L3 CZ counts → 04 L4 Aer noise → 05 L5 CUDA-Q →
06 S2-b structured gates → 07 H0 hardware → 08 month plan.
"""
    open(os.path.join(ROOT, "reports", "PROJECT_STATUS.md"), "w").write(status)
    print(table)


if __name__ == "__main__":
    main()
