#!/usr/bin/env python3
"""Regenerate validation/gates.md and reports/PROJECT_STATUS.md from validation/*.json (no hand-typed numbers)."""
import glob
import json
import os
import time

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
GATES = [  # gate, description (manual Step 10), where it runs
    ("E1", "[G_a(x),H]=0; 82-dim kernel; sector split; two builders agree to 1e-12", "cloud/laptop CPU"),
    ("E2", "counts of Table 2; codec round trip on all 2x3 states; random-bitstring acceptance ~0.15%", "cloud/laptop CPU"),
    ("E3", "2x3 and 2x4 references (Table 1); static sectors; dt = pi/W per sector", "cloud/laptop CPU"),
    ("S1", "emulated support recall >= 0.9 at f >= 0.1 with the production budget; controls table", "cloud/laptop CPU"),
    ("CS", "structure of the terms in codeword space (input to S2)", "cloud/laptop CPU"),
    ("L2", "Qiskit circuits reproduce the numpy reference at 2x2", "laptop"),
    ("L3", "transpiled CZ counts (S2 measurement)", "laptop"),
    ("L4", "Aer noise-model sampling at 2x2 (S3 preparation)", "laptop"),
    ("L5", "CUDA-Q circuits reproduce the numpy reference at 2x2", "laptop GPU"),
    ("S2", "routed CZ per coarse step <= 500 on the target map (<= 250 at 2x2); compiled circuits leak-free", "laptop"),
    ("S2D", "device-resolved budget (prompts/12): mean clean-shot fraction f >= 0.1 (worst >= 0.05) per lattice and device; k=1 counts reproduce S2; shot rule of eq. (5)", "laptop"),
    ("L4_fez", "L4 with NoiseModel.from_backend(FakeFez) and transpilation onto the snapshot (H0 rehearsal)", "laptop"),
    ("S3", "Aer device-model recall >= 0.9 for the production set; shot budget fixed", "desktop GPU"),
    ("S3_smoke", "S3 pipeline smoke test at 2x3 B=1 (2 shots per circuit: NOT the production budget)", "laptop"),
    ("H0P", "H0 preparation on a calibration snapshot: frozen circuit set leak-free, predicted yield per repetition, readout confusion, Ritz consistency", "laptop"),
    ("H0_dryrun", "gate H0 run on the SamplerV2 dry-run counts (data/hardware/H0_dryrun)", "laptop"),
    ("H0P_ibm_fez", "H0P re-predicted on the live ibm_fez calibration of the session day (prompts/15 D1: the circuits stay frozen, only the prediction is recomputed)", "laptop"),
    ("H0P_rehearsal", "H0P on FakeFez with the D3' shot plan through the sampling cache (prompts/16)", "laptop"),
    ("H0", "2x2 hardware: decoder validity, bit order, parity checks; measured f within 30% of the model", "QPU"),
    ("H1", "2x3 B=0: certified interval of width <= 0.1 containing the exact E0; recall >= 0.8", "QPU"),
    ("H2", "2x3 B=1: cluster energy certified to +-rH <= 0.15; V(1), V(2) intervals containing exact values", "QPU"),
    ("P1", "primary endpoint curves with bootstrap bands", "laptop"),
    ("M1", "ML uses credited only under Step 7.5", "desktop GPU"),
]


def main():
    rows = []
    for g, desc, where in GATES:
        p = os.path.join(ROOT, "validation", f"{g}.json")
        if os.path.exists(p):
            d = json.load(open(p))
            nf = sum(1 for c in d["criteria"] if not c["passed"])
            status = f"**{d['status']}** ({len(d['criteria'])} criteria, {nf} failing, {d['runtime_s']:.0f} s, {d['environment']['timestamp']}, commit {d['environment']['git_commit']})"
        else:
            status = "open"
        rows.append(f"| {g} | {desc} | {where} | {status} |")
    table = "| gate | check (manual Step 10) | runs on | status |\n|---|---|---|---|\n" + "\n".join(rows)
    stamp = time.strftime("%Y-%m-%d %H:%M UTC", time.gmtime())
    open(os.path.join(ROOT, "validation", "gates.md"), "w").write(f"# Gate table (generated by scripts/update_status.py, {stamp})\n\n{table}\n")
    status = f"""# Project status (generated by scripts/update_status.py, {stamp})

{table}

## Reports

| report | content |
|---|---|
| `reports/E1_gauss_law_two_builders.md` | Gauss law, kernel, two-builder agreement, 2x2 spectrum vs manual |
| `reports/E2_counts_codewords_decoder.md` | Table 2, vertex tables, codewords, decoder acceptance |
| `reports/E3_exact_references.md` | Table 1, static sectors, derived quantities, clusters, j_max=1 truncation |
| `reports/S1_support_emulation_controls.md` | reachability, Table 4, production-budget recall, Table 3, ML ranker, 2x4 |
| `reports/circuit_structure.md` | term structure in codeword space, 2x2 plaquette pair rotation, IR gate counts |
| `reports/laptop_vs_hpc_plan.md` | what runs on the laptop within 30 min and what needs desktop/cluster/QPU |
| `reports/S2_structured_circuits.md`, `reports/S2_fixed_angle_circuits.md`, `reports/S2_escalation_analysis.md` | gate S2, the fixed-angle cost floor, and the escalation diagnostics |
| `reports/S2D_device_budgets.md` | gate S2D: per-device gate counts, clean-shot fraction f, shot budget, 2x3 per-shot cost |
| `reports/H0P_heron_preparation.md` | gate H0P: the frozen H0 circuit set, yield versus CZ by repetition, readout confusion, Ritz consistency |
| `reports/H0_prereg_draft.md` | the preregistration paragraph for the first QPU session (generated from validation/H0P.json) |
| `reports/H0P_ibm_fez_heron_preparation.md`, `reports/H0_prereg_ibm_fez.md` | the session day's prediction and preregistration, recomputed on the live ibm_fez calibration (written when gate H0P_ibm_fez runs) |
| `reports/H0_support_plan_FakeFez.md`, `reports/H0_support_plan_live_20260921.md` | the D3' shot plan (prompts/16): per-state expected clean counts, N4 per sector, P(saturation) against the frozen plan |
| `reports/H0P_rehearsal_heron_preparation.md` | the FakeFez rehearsal of the D3' plan through the sampling cache (prompts/16 A'3) |
| `reports/H0P_ibm_fez_escalation_20260921.md` | why the frozen shot plan made criterion 3 a coin flip, and the decision D3' |
| `reports/H0_dryrun_hardware_2x2.md` | gate H0 on the dry-run counts: the analysis the real session will run unchanged |
| `reports/S3_smoke_device_model.md` | the S3 job script end to end at 2x3 (pipeline smoke test, laptop CPU) |
| `proposal/amendment_01_devices_and_budgets.md` | draft amendment for the owner (generated by `scripts/make_amendment.py`) |
| `reports/L*.md` | laptop gates (written when they run) |

## Next actions (prompts/)

00 bootstrap + push → 01 L1 reproduce → 02 L2 Qiskit → 03 L3 CZ counts → 04 L4 Aer noise → 05 L5 CUDA-Q →
06 S2-b structured gates (S2 FAIL on the CZ budget) → 11 S2 escalation (fixed-angle floor measured) →
12 devices and budgets (S2D, L4_fez, amendment 01) → 13 H0 preparation on Heron + the S3 desktop job
(H0P, H0_dryrun, S3_smoke, `slurm/s3_2x3.sbatch`) → owner decision on the 2x3 device and the shot quota
(section 5 of `proposal/amendment_01_devices_and_budgets.md`) → 15 the H0 session on ibm_fez: part A
(live-backend paths, submit/retrieve split, QPU-time estimate) then part B (preflight, the day's
prediction, canary, main submission, gate H0) → 16 the corrected shot plan D3' (part A': the plan, the
sampling cache, the per-state support prediction and the FakeFez rehearsal; part B' the session day) →
07 H0 hardware session.
"""
    open(os.path.join(ROOT, "reports", "PROJECT_STATUS.md"), "w").write(status)
    print(table)


if __name__ == "__main__":
    main()
